services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/futbot-front
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - frontend_node_modules:/app/futbot-front/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  frontend_node_modules: